// Code generated by MockGen. DO NOT EDIT.
// Source: google.golang.org/adk/v2/agent (interfaces: Context,InvocationContext)
//
// Generated by this command:
//
//	mockgen -destination=dbosadk/mocks_test.go -package=dbosadk -mock_names Context=MockAgentContext,InvocationContext=MockInvocationContext google.golang.org/adk/v2/agent Context,InvocationContext
//

// Package dbosadk is a generated GoMock package.
package dbosadk

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
	agent "google.golang.org/adk/v2/agent"
	memory "google.golang.org/adk/v2/memory"
	session "google.golang.org/adk/v2/session"
	toolconfirmation "google.golang.org/adk/v2/tool/toolconfirmation"
	genai "google.golang.org/genai"
)

// MockAgentContext is a mock of Context interface.
type MockAgentContext struct {
	ctrl     *gomock.Controller
	recorder *MockAgentContextMockRecorder
	isgomock struct{}
}

// MockAgentContextMockRecorder is the mock recorder for MockAgentContext.
type MockAgentContextMockRecorder struct {
	mock *MockAgentContext
}

// NewMockAgentContext creates a new mock instance.
func NewMockAgentContext(ctrl *gomock.Controller) *MockAgentContext {
	mock := &MockAgentContext{ctrl: ctrl}
	mock.recorder = &MockAgentContextMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentContext) EXPECT() *MockAgentContextMockRecorder {
	return m.recorder
}

// Actions mocks base method.
func (m *MockAgentContext) Actions() *session.EventActions {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Actions")
	ret0, _ := ret[0].(*session.EventActions)
	return ret0
}

// Actions indicates an expected call of Actions.
func (mr *MockAgentContextMockRecorder) Actions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Actions", reflect.TypeOf((*MockAgentContext)(nil).Actions))
}

// Agent mocks base method.
func (m *MockAgentContext) Agent() agent.Agent {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Agent")
	ret0, _ := ret[0].(agent.Agent)
	return ret0
}

// Agent indicates an expected call of Agent.
func (mr *MockAgentContextMockRecorder) Agent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Agent", reflect.TypeOf((*MockAgentContext)(nil).Agent))
}

// AgentName mocks base method.
func (m *MockAgentContext) AgentName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AgentName")
	ret0, _ := ret[0].(string)
	return ret0
}

// AgentName indicates an expected call of AgentName.
func (mr *MockAgentContextMockRecorder) AgentName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AgentName", reflect.TypeOf((*MockAgentContext)(nil).AgentName))
}

// AppName mocks base method.
func (m *MockAgentContext) AppName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppName")
	ret0, _ := ret[0].(string)
	return ret0
}

// AppName indicates an expected call of AppName.
func (mr *MockAgentContextMockRecorder) AppName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppName", reflect.TypeOf((*MockAgentContext)(nil).AppName))
}

// Artifacts mocks base method.
func (m *MockAgentContext) Artifacts() agent.Artifacts {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Artifacts")
	ret0, _ := ret[0].(agent.Artifacts)
	return ret0
}

// Artifacts indicates an expected call of Artifacts.
func (mr *MockAgentContextMockRecorder) Artifacts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Artifacts", reflect.TypeOf((*MockAgentContext)(nil).Artifacts))
}

// Branch mocks base method.
func (m *MockAgentContext) Branch() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Branch")
	ret0, _ := ret[0].(string)
	return ret0
}

// Branch indicates an expected call of Branch.
func (mr *MockAgentContextMockRecorder) Branch() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Branch", reflect.TypeOf((*MockAgentContext)(nil).Branch))
}

// Deadline mocks base method.
func (m *MockAgentContext) Deadline() (time.Time, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deadline")
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Deadline indicates an expected call of Deadline.
func (mr *MockAgentContextMockRecorder) Deadline() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deadline", reflect.TypeOf((*MockAgentContext)(nil).Deadline))
}

// Done mocks base method.
func (m *MockAgentContext) Done() <-chan struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Done")
	ret0, _ := ret[0].(<-chan struct{})
	return ret0
}

// Done indicates an expected call of Done.
func (mr *MockAgentContextMockRecorder) Done() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Done", reflect.TypeOf((*MockAgentContext)(nil).Done))
}

// EndInvocation mocks base method.
func (m *MockAgentContext) EndInvocation() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "EndInvocation")
}

// EndInvocation indicates an expected call of EndInvocation.
func (mr *MockAgentContextMockRecorder) EndInvocation() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndInvocation", reflect.TypeOf((*MockAgentContext)(nil).EndInvocation))
}

// Ended mocks base method.
func (m *MockAgentContext) Ended() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ended")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Ended indicates an expected call of Ended.
func (mr *MockAgentContextMockRecorder) Ended() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ended", reflect.TypeOf((*MockAgentContext)(nil).Ended))
}

// Err mocks base method.
func (m *MockAgentContext) Err() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Err")
	ret0, _ := ret[0].(error)
	return ret0
}

// Err indicates an expected call of Err.
func (mr *MockAgentContextMockRecorder) Err() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Err", reflect.TypeOf((*MockAgentContext)(nil).Err))
}

// FunctionCallID mocks base method.
func (m *MockAgentContext) FunctionCallID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FunctionCallID")
	ret0, _ := ret[0].(string)
	return ret0
}

// FunctionCallID indicates an expected call of FunctionCallID.
func (mr *MockAgentContextMockRecorder) FunctionCallID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FunctionCallID", reflect.TypeOf((*MockAgentContext)(nil).FunctionCallID))
}

// InvocationID mocks base method.
func (m *MockAgentContext) InvocationID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvocationID")
	ret0, _ := ret[0].(string)
	return ret0
}

// InvocationID indicates an expected call of InvocationID.
func (mr *MockAgentContextMockRecorder) InvocationID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvocationID", reflect.TypeOf((*MockAgentContext)(nil).InvocationID))
}

// IsolationScope mocks base method.
func (m *MockAgentContext) IsolationScope() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsolationScope")
	ret0, _ := ret[0].(string)
	return ret0
}

// IsolationScope indicates an expected call of IsolationScope.
func (mr *MockAgentContextMockRecorder) IsolationScope() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsolationScope", reflect.TypeOf((*MockAgentContext)(nil).IsolationScope))
}

// Memory mocks base method.
func (m *MockAgentContext) Memory() agent.Memory {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Memory")
	ret0, _ := ret[0].(agent.Memory)
	return ret0
}

// Memory indicates an expected call of Memory.
func (mr *MockAgentContextMockRecorder) Memory() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Memory", reflect.TypeOf((*MockAgentContext)(nil).Memory))
}

// OutputForAncestors mocks base method.
func (m *MockAgentContext) OutputForAncestors() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OutputForAncestors")
	ret0, _ := ret[0].([]string)
	return ret0
}

// OutputForAncestors indicates an expected call of OutputForAncestors.
func (mr *MockAgentContextMockRecorder) OutputForAncestors() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OutputForAncestors", reflect.TypeOf((*MockAgentContext)(nil).OutputForAncestors))
}

// Path mocks base method.
func (m *MockAgentContext) Path() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Path")
	ret0, _ := ret[0].(string)
	return ret0
}

// Path indicates an expected call of Path.
func (mr *MockAgentContextMockRecorder) Path() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Path", reflect.TypeOf((*MockAgentContext)(nil).Path))
}

// ReadonlyState mocks base method.
func (m *MockAgentContext) ReadonlyState() session.ReadonlyState {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadonlyState")
	ret0, _ := ret[0].(session.ReadonlyState)
	return ret0
}

// ReadonlyState indicates an expected call of ReadonlyState.
func (mr *MockAgentContextMockRecorder) ReadonlyState() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadonlyState", reflect.TypeOf((*MockAgentContext)(nil).ReadonlyState))
}

// RequestConfirmation mocks base method.
func (m *MockAgentContext) RequestConfirmation(hint string, payload any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestConfirmation", hint, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequestConfirmation indicates an expected call of RequestConfirmation.
func (mr *MockAgentContextMockRecorder) RequestConfirmation(hint, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestConfirmation", reflect.TypeOf((*MockAgentContext)(nil).RequestConfirmation), hint, payload)
}

// ResumedInput mocks base method.
func (m *MockAgentContext) ResumedInput(interruptID string) (any, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResumedInput", interruptID)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// ResumedInput indicates an expected call of ResumedInput.
func (mr *MockAgentContextMockRecorder) ResumedInput(interruptID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResumedInput", reflect.TypeOf((*MockAgentContext)(nil).ResumedInput), interruptID)
}

// RunConfig mocks base method.
func (m *MockAgentContext) RunConfig() *agent.RunConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunConfig")
	ret0, _ := ret[0].(*agent.RunConfig)
	return ret0
}

// RunConfig indicates an expected call of RunConfig.
func (mr *MockAgentContextMockRecorder) RunConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunConfig", reflect.TypeOf((*MockAgentContext)(nil).RunConfig))
}

// RunID mocks base method.
func (m *MockAgentContext) RunID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunID")
	ret0, _ := ret[0].(string)
	return ret0
}

// RunID indicates an expected call of RunID.
func (mr *MockAgentContextMockRecorder) RunID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunID", reflect.TypeOf((*MockAgentContext)(nil).RunID))
}

// SearchMemory mocks base method.
func (m *MockAgentContext) SearchMemory(ctx context.Context, query string) (*memory.SearchResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchMemory", ctx, query)
	ret0, _ := ret[0].(*memory.SearchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchMemory indicates an expected call of SearchMemory.
func (mr *MockAgentContextMockRecorder) SearchMemory(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchMemory", reflect.TypeOf((*MockAgentContext)(nil).SearchMemory), ctx, query)
}

// Session mocks base method.
func (m *MockAgentContext) Session() session.Session {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Session")
	ret0, _ := ret[0].(session.Session)
	return ret0
}

// Session indicates an expected call of Session.
func (mr *MockAgentContextMockRecorder) Session() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Session", reflect.TypeOf((*MockAgentContext)(nil).Session))
}

// SessionID mocks base method.
func (m *MockAgentContext) SessionID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SessionID")
	ret0, _ := ret[0].(string)
	return ret0
}

// SessionID indicates an expected call of SessionID.
func (mr *MockAgentContextMockRecorder) SessionID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SessionID", reflect.TypeOf((*MockAgentContext)(nil).SessionID))
}

// State mocks base method.
func (m *MockAgentContext) State() session.State {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "State")
	ret0, _ := ret[0].(session.State)
	return ret0
}

// State indicates an expected call of State.
func (mr *MockAgentContextMockRecorder) State() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "State", reflect.TypeOf((*MockAgentContext)(nil).State))
}

// SubScheduler mocks base method.
func (m *MockAgentContext) SubScheduler() agent.DynamicSubScheduler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubScheduler")
	ret0, _ := ret[0].(agent.DynamicSubScheduler)
	return ret0
}

// SubScheduler indicates an expected call of SubScheduler.
func (mr *MockAgentContextMockRecorder) SubScheduler() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubScheduler", reflect.TypeOf((*MockAgentContext)(nil).SubScheduler))
}

// ToolConfirmation mocks base method.
func (m *MockAgentContext) ToolConfirmation() *toolconfirmation.ToolConfirmation {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToolConfirmation")
	ret0, _ := ret[0].(*toolconfirmation.ToolConfirmation)
	return ret0
}

// ToolConfirmation indicates an expected call of ToolConfirmation.
func (mr *MockAgentContextMockRecorder) ToolConfirmation() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToolConfirmation", reflect.TypeOf((*MockAgentContext)(nil).ToolConfirmation))
}

// UserContent mocks base method.
func (m *MockAgentContext) UserContent() *genai.Content {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserContent")
	ret0, _ := ret[0].(*genai.Content)
	return ret0
}

// UserContent indicates an expected call of UserContent.
func (mr *MockAgentContextMockRecorder) UserContent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserContent", reflect.TypeOf((*MockAgentContext)(nil).UserContent))
}

// UserID mocks base method.
func (m *MockAgentContext) UserID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserID")
	ret0, _ := ret[0].(string)
	return ret0
}

// UserID indicates an expected call of UserID.
func (mr *MockAgentContextMockRecorder) UserID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserID", reflect.TypeOf((*MockAgentContext)(nil).UserID))
}

// Value mocks base method.
func (m *MockAgentContext) Value(key any) any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Value", key)
	ret0, _ := ret[0].(any)
	return ret0
}

// Value indicates an expected call of Value.
func (mr *MockAgentContextMockRecorder) Value(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Value", reflect.TypeOf((*MockAgentContext)(nil).Value), key)
}

// WithAgentCancel mocks base method.
func (m *MockAgentContext) WithAgentCancel() (agent.Context, context.CancelFunc) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithAgentCancel")
	ret0, _ := ret[0].(agent.Context)
	ret1, _ := ret[1].(context.CancelFunc)
	return ret0, ret1
}

// WithAgentCancel indicates an expected call of WithAgentCancel.
func (mr *MockAgentContextMockRecorder) WithAgentCancel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithAgentCancel", reflect.TypeOf((*MockAgentContext)(nil).WithAgentCancel))
}

// WithAgentContext mocks base method.
func (m *MockAgentContext) WithAgentContext(ctx context.Context) agent.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithAgentContext", ctx)
	ret0, _ := ret[0].(agent.Context)
	return ret0
}

// WithAgentContext indicates an expected call of WithAgentContext.
func (mr *MockAgentContextMockRecorder) WithAgentContext(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithAgentContext", reflect.TypeOf((*MockAgentContext)(nil).WithAgentContext), ctx)
}

// WithAgentTimeout mocks base method.
func (m *MockAgentContext) WithAgentTimeout(timeout time.Duration) (agent.Context, context.CancelFunc) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithAgentTimeout", timeout)
	ret0, _ := ret[0].(agent.Context)
	ret1, _ := ret[1].(context.CancelFunc)
	return ret0, ret1
}

// WithAgentTimeout indicates an expected call of WithAgentTimeout.
func (mr *MockAgentContextMockRecorder) WithAgentTimeout(timeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithAgentTimeout", reflect.TypeOf((*MockAgentContext)(nil).WithAgentTimeout), timeout)
}

// WithContext mocks base method.
func (m *MockAgentContext) WithContext(ctx context.Context) agent.InvocationContext {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithContext", ctx)
	ret0, _ := ret[0].(agent.InvocationContext)
	return ret0
}

// WithContext indicates an expected call of WithContext.
func (mr *MockAgentContextMockRecorder) WithContext(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithContext", reflect.TypeOf((*MockAgentContext)(nil).WithContext), ctx)
}

// WithDelta mocks base method.
func (m *MockAgentContext) WithDelta(d *agent.CommonContextDelta) agent.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithDelta", d)
	ret0, _ := ret[0].(agent.Context)
	return ret0
}

// WithDelta indicates an expected call of WithDelta.
func (mr *MockAgentContextMockRecorder) WithDelta(d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithDelta", reflect.TypeOf((*MockAgentContext)(nil).WithDelta), d)
}

// WithICDelta mocks base method.
func (m *MockAgentContext) WithICDelta(d *agent.InvocationContextDelta) agent.InvocationContext {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithICDelta", d)
	ret0, _ := ret[0].(agent.InvocationContext)
	return ret0
}

// WithICDelta indicates an expected call of WithICDelta.
func (mr *MockAgentContextMockRecorder) WithICDelta(d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithICDelta", reflect.TypeOf((*MockAgentContext)(nil).WithICDelta), d)
}

// MockInvocationContext is a mock of InvocationContext interface.
type MockInvocationContext struct {
	ctrl     *gomock.Controller
	recorder *MockInvocationContextMockRecorder
	isgomock struct{}
}

// MockInvocationContextMockRecorder is the mock recorder for MockInvocationContext.
type MockInvocationContextMockRecorder struct {
	mock *MockInvocationContext
}

// NewMockInvocationContext creates a new mock instance.
func NewMockInvocationContext(ctrl *gomock.Controller) *MockInvocationContext {
	mock := &MockInvocationContext{ctrl: ctrl}
	mock.recorder = &MockInvocationContextMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInvocationContext) EXPECT() *MockInvocationContextMockRecorder {
	return m.recorder
}

// Agent mocks base method.
func (m *MockInvocationContext) Agent() agent.Agent {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Agent")
	ret0, _ := ret[0].(agent.Agent)
	return ret0
}

// Agent indicates an expected call of Agent.
func (mr *MockInvocationContextMockRecorder) Agent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Agent", reflect.TypeOf((*MockInvocationContext)(nil).Agent))
}

// Artifacts mocks base method.
func (m *MockInvocationContext) Artifacts() agent.Artifacts {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Artifacts")
	ret0, _ := ret[0].(agent.Artifacts)
	return ret0
}

// Artifacts indicates an expected call of Artifacts.
func (mr *MockInvocationContextMockRecorder) Artifacts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Artifacts", reflect.TypeOf((*MockInvocationContext)(nil).Artifacts))
}

// Branch mocks base method.
func (m *MockInvocationContext) Branch() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Branch")
	ret0, _ := ret[0].(string)
	return ret0
}

// Branch indicates an expected call of Branch.
func (mr *MockInvocationContextMockRecorder) Branch() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Branch", reflect.TypeOf((*MockInvocationContext)(nil).Branch))
}

// Deadline mocks base method.
func (m *MockInvocationContext) Deadline() (time.Time, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deadline")
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Deadline indicates an expected call of Deadline.
func (mr *MockInvocationContextMockRecorder) Deadline() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deadline", reflect.TypeOf((*MockInvocationContext)(nil).Deadline))
}

// Done mocks base method.
func (m *MockInvocationContext) Done() <-chan struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Done")
	ret0, _ := ret[0].(<-chan struct{})
	return ret0
}

// Done indicates an expected call of Done.
func (mr *MockInvocationContextMockRecorder) Done() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Done", reflect.TypeOf((*MockInvocationContext)(nil).Done))
}

// EndInvocation mocks base method.
func (m *MockInvocationContext) EndInvocation() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "EndInvocation")
}

// EndInvocation indicates an expected call of EndInvocation.
func (mr *MockInvocationContextMockRecorder) EndInvocation() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndInvocation", reflect.TypeOf((*MockInvocationContext)(nil).EndInvocation))
}

// Ended mocks base method.
func (m *MockInvocationContext) Ended() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ended")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Ended indicates an expected call of Ended.
func (mr *MockInvocationContextMockRecorder) Ended() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ended", reflect.TypeOf((*MockInvocationContext)(nil).Ended))
}

// Err mocks base method.
func (m *MockInvocationContext) Err() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Err")
	ret0, _ := ret[0].(error)
	return ret0
}

// Err indicates an expected call of Err.
func (mr *MockInvocationContextMockRecorder) Err() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Err", reflect.TypeOf((*MockInvocationContext)(nil).Err))
}

// InvocationID mocks base method.
func (m *MockInvocationContext) InvocationID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvocationID")
	ret0, _ := ret[0].(string)
	return ret0
}

// InvocationID indicates an expected call of InvocationID.
func (mr *MockInvocationContextMockRecorder) InvocationID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvocationID", reflect.TypeOf((*MockInvocationContext)(nil).InvocationID))
}

// IsolationScope mocks base method.
func (m *MockInvocationContext) IsolationScope() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsolationScope")
	ret0, _ := ret[0].(string)
	return ret0
}

// IsolationScope indicates an expected call of IsolationScope.
func (mr *MockInvocationContextMockRecorder) IsolationScope() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsolationScope", reflect.TypeOf((*MockInvocationContext)(nil).IsolationScope))
}

// Memory mocks base method.
func (m *MockInvocationContext) Memory() agent.Memory {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Memory")
	ret0, _ := ret[0].(agent.Memory)
	return ret0
}

// Memory indicates an expected call of Memory.
func (mr *MockInvocationContextMockRecorder) Memory() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Memory", reflect.TypeOf((*MockInvocationContext)(nil).Memory))
}

// ResumedInput mocks base method.
func (m *MockInvocationContext) ResumedInput(interruptID string) (any, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResumedInput", interruptID)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// ResumedInput indicates an expected call of ResumedInput.
func (mr *MockInvocationContextMockRecorder) ResumedInput(interruptID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResumedInput", reflect.TypeOf((*MockInvocationContext)(nil).ResumedInput), interruptID)
}

// RunConfig mocks base method.
func (m *MockInvocationContext) RunConfig() *agent.RunConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunConfig")
	ret0, _ := ret[0].(*agent.RunConfig)
	return ret0
}

// RunConfig indicates an expected call of RunConfig.
func (mr *MockInvocationContextMockRecorder) RunConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunConfig", reflect.TypeOf((*MockInvocationContext)(nil).RunConfig))
}

// Session mocks base method.
func (m *MockInvocationContext) Session() session.Session {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Session")
	ret0, _ := ret[0].(session.Session)
	return ret0
}

// Session indicates an expected call of Session.
func (mr *MockInvocationContextMockRecorder) Session() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Session", reflect.TypeOf((*MockInvocationContext)(nil).Session))
}

// UserContent mocks base method.
func (m *MockInvocationContext) UserContent() *genai.Content {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserContent")
	ret0, _ := ret[0].(*genai.Content)
	return ret0
}

// UserContent indicates an expected call of UserContent.
func (mr *MockInvocationContextMockRecorder) UserContent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserContent", reflect.TypeOf((*MockInvocationContext)(nil).UserContent))
}

// Value mocks base method.
func (m *MockInvocationContext) Value(key any) any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Value", key)
	ret0, _ := ret[0].(any)
	return ret0
}

// Value indicates an expected call of Value.
func (mr *MockInvocationContextMockRecorder) Value(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Value", reflect.TypeOf((*MockInvocationContext)(nil).Value), key)
}

// WithContext mocks base method.
func (m *MockInvocationContext) WithContext(ctx context.Context) agent.InvocationContext {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithContext", ctx)
	ret0, _ := ret[0].(agent.InvocationContext)
	return ret0
}

// WithContext indicates an expected call of WithContext.
func (mr *MockInvocationContextMockRecorder) WithContext(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithContext", reflect.TypeOf((*MockInvocationContext)(nil).WithContext), ctx)
}

// WithICDelta mocks base method.
func (m *MockInvocationContext) WithICDelta(d *agent.InvocationContextDelta) agent.InvocationContext {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithICDelta", d)
	ret0, _ := ret[0].(agent.InvocationContext)
	return ret0
}

// WithICDelta indicates an expected call of WithICDelta.
func (mr *MockInvocationContextMockRecorder) WithICDelta(d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithICDelta", reflect.TypeOf((*MockInvocationContext)(nil).WithICDelta), d)
}
