// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dbos-inc/dbos-transact-golang/dbos (interfaces: Context)
//
// Generated by this command:
//
//	mockgen -destination=dbosadk/mocks_dbos_test.go -package=dbosadk -mock_names Context=MockDBOSContext github.com/dbos-inc/dbos-transact-golang/dbos Context
//

// Package dbosadk is a generated GoMock package.
package dbosadk

import (
	context "context"
	reflect "reflect"
	time "time"

	dbos "github.com/dbos-inc/dbos-transact-golang/dbos"
	gomock "go.uber.org/mock/gomock"
)

// MockDBOSContext is a mock of Context interface.
type MockDBOSContext struct {
	ctrl     *gomock.Controller
	recorder *MockDBOSContextMockRecorder
	isgomock struct{}
}

// MockDBOSContextMockRecorder is the mock recorder for MockDBOSContext.
type MockDBOSContextMockRecorder struct {
	mock *MockDBOSContext
}

// NewMockDBOSContext creates a new mock instance.
func NewMockDBOSContext(ctrl *gomock.Controller) *MockDBOSContext {
	mock := &MockDBOSContext{ctrl: ctrl}
	mock.recorder = &MockDBOSContextMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBOSContext) EXPECT() *MockDBOSContextMockRecorder {
	return m.recorder
}

// ApplySchedules mocks base method.
func (m *MockDBOSContext) ApplySchedules(arg0 dbos.Client, schedules []dbos.ScheduleSpec) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplySchedules", arg0, schedules)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplySchedules indicates an expected call of ApplySchedules.
func (mr *MockDBOSContextMockRecorder) ApplySchedules(arg0, schedules any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplySchedules", reflect.TypeOf((*MockDBOSContext)(nil).ApplySchedules), arg0, schedules)
}

// BackfillSchedule mocks base method.
func (m *MockDBOSContext) BackfillSchedule(arg0 dbos.Client, scheduleName string, start, end time.Time) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BackfillSchedule", arg0, scheduleName, start, end)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BackfillSchedule indicates an expected call of BackfillSchedule.
func (mr *MockDBOSContextMockRecorder) BackfillSchedule(arg0, scheduleName, start, end any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BackfillSchedule", reflect.TypeOf((*MockDBOSContext)(nil).BackfillSchedule), arg0, scheduleName, start, end)
}

// CancelWorkflow mocks base method.
func (m *MockDBOSContext) CancelWorkflow(arg0 dbos.Client, workflowID string, opts ...dbos.CancelWorkflowOption) error {
	m.ctrl.T.Helper()
	varargs := []any{arg0, workflowID}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CancelWorkflow", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelWorkflow indicates an expected call of CancelWorkflow.
func (mr *MockDBOSContextMockRecorder) CancelWorkflow(arg0, workflowID any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, workflowID}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelWorkflow", reflect.TypeOf((*MockDBOSContext)(nil).CancelWorkflow), varargs...)
}

// CancelWorkflows mocks base method.
func (m *MockDBOSContext) CancelWorkflows(arg0 dbos.Client, workflowIDs []string, opts ...dbos.CancelWorkflowOption) error {
	m.ctrl.T.Helper()
	varargs := []any{arg0, workflowIDs}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CancelWorkflows", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelWorkflows indicates an expected call of CancelWorkflows.
func (mr *MockDBOSContextMockRecorder) CancelWorkflows(arg0, workflowIDs any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, workflowIDs}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelWorkflows", reflect.TypeOf((*MockDBOSContext)(nil).CancelWorkflows), varargs...)
}

// CloseStream mocks base method.
func (m *MockDBOSContext) CloseStream(arg0 dbos.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseStream", arg0, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseStream indicates an expected call of CloseStream.
func (mr *MockDBOSContextMockRecorder) CloseStream(arg0, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseStream", reflect.TypeOf((*MockDBOSContext)(nil).CloseStream), arg0, key)
}

// CreateSchedule mocks base method.
func (m *MockDBOSContext) CreateSchedule(arg0 dbos.Client, spec dbos.ScheduleSpec) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSchedule", arg0, spec)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSchedule indicates an expected call of CreateSchedule.
func (mr *MockDBOSContextMockRecorder) CreateSchedule(arg0, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSchedule", reflect.TypeOf((*MockDBOSContext)(nil).CreateSchedule), arg0, spec)
}

// Deadline mocks base method.
func (m *MockDBOSContext) Deadline() (time.Time, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deadline")
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Deadline indicates an expected call of Deadline.
func (mr *MockDBOSContextMockRecorder) Deadline() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deadline", reflect.TypeOf((*MockDBOSContext)(nil).Deadline))
}

// DeleteQueue mocks base method.
func (m *MockDBOSContext) DeleteQueue(arg0 dbos.Client, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteQueue", arg0, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteQueue indicates an expected call of DeleteQueue.
func (mr *MockDBOSContextMockRecorder) DeleteQueue(arg0, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteQueue", reflect.TypeOf((*MockDBOSContext)(nil).DeleteQueue), arg0, name)
}

// DeleteSchedule mocks base method.
func (m *MockDBOSContext) DeleteSchedule(arg0 dbos.Client, scheduleName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSchedule", arg0, scheduleName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSchedule indicates an expected call of DeleteSchedule.
func (mr *MockDBOSContextMockRecorder) DeleteSchedule(arg0, scheduleName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSchedule", reflect.TypeOf((*MockDBOSContext)(nil).DeleteSchedule), arg0, scheduleName)
}

// DeleteWorkflows mocks base method.
func (m *MockDBOSContext) DeleteWorkflows(arg0 dbos.Client, workflowIDs []string, opts ...dbos.DeleteWorkflowOption) error {
	m.ctrl.T.Helper()
	varargs := []any{arg0, workflowIDs}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteWorkflows", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWorkflows indicates an expected call of DeleteWorkflows.
func (mr *MockDBOSContextMockRecorder) DeleteWorkflows(arg0, workflowIDs any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, workflowIDs}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWorkflows", reflect.TypeOf((*MockDBOSContext)(nil).DeleteWorkflows), varargs...)
}

// DeprecatePatch mocks base method.
func (m *MockDBOSContext) DeprecatePatch(arg0 dbos.Context, patchName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeprecatePatch", arg0, patchName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeprecatePatch indicates an expected call of DeprecatePatch.
func (mr *MockDBOSContextMockRecorder) DeprecatePatch(arg0, patchName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeprecatePatch", reflect.TypeOf((*MockDBOSContext)(nil).DeprecatePatch), arg0, patchName)
}

// Done mocks base method.
func (m *MockDBOSContext) Done() <-chan struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Done")
	ret0, _ := ret[0].(<-chan struct{})
	return ret0
}

// Done indicates an expected call of Done.
func (mr *MockDBOSContextMockRecorder) Done() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Done", reflect.TypeOf((*MockDBOSContext)(nil).Done))
}

// Enqueue mocks base method.
func (m *MockDBOSContext) Enqueue(arg0 dbos.Client, queueName, workflowName string, input any, opts ...dbos.EnqueueOption) (dbos.WorkflowHandle[any], error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, queueName, workflowName, input}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Enqueue", varargs...)
	ret0, _ := ret[0].(dbos.WorkflowHandle[any])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MockDBOSContextMockRecorder) Enqueue(arg0, queueName, workflowName, input any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, queueName, workflowName, input}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*MockDBOSContext)(nil).Enqueue), varargs...)
}

// Err mocks base method.
func (m *MockDBOSContext) Err() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Err")
	ret0, _ := ret[0].(error)
	return ret0
}

// Err indicates an expected call of Err.
func (mr *MockDBOSContextMockRecorder) Err() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Err", reflect.TypeOf((*MockDBOSContext)(nil).Err))
}

// ForkWorkflow mocks base method.
func (m *MockDBOSContext) ForkWorkflow(arg0 dbos.Client, input dbos.ForkWorkflowInput) (dbos.WorkflowHandle[any], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForkWorkflow", arg0, input)
	ret0, _ := ret[0].(dbos.WorkflowHandle[any])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ForkWorkflow indicates an expected call of ForkWorkflow.
func (mr *MockDBOSContextMockRecorder) ForkWorkflow(arg0, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForkWorkflow", reflect.TypeOf((*MockDBOSContext)(nil).ForkWorkflow), arg0, input)
}

// ForkWorkflows mocks base method.
func (m *MockDBOSContext) ForkWorkflows(arg0 dbos.Client, input dbos.ForkWorkflowsInput) ([]dbos.WorkflowHandle[any], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForkWorkflows", arg0, input)
	ret0, _ := ret[0].([]dbos.WorkflowHandle[any])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ForkWorkflows indicates an expected call of ForkWorkflows.
func (mr *MockDBOSContextMockRecorder) ForkWorkflows(arg0, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForkWorkflows", reflect.TypeOf((*MockDBOSContext)(nil).ForkWorkflows), arg0, input)
}

// From mocks base method.
func (m *MockDBOSContext) From(arg0 dbos.Context, ctx context.Context) dbos.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "From", arg0, ctx)
	ret0, _ := ret[0].(dbos.Context)
	return ret0
}

// From indicates an expected call of From.
func (mr *MockDBOSContextMockRecorder) From(arg0, ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "From", reflect.TypeOf((*MockDBOSContext)(nil).From), arg0, ctx)
}

// GetApplicationID mocks base method.
func (m *MockDBOSContext) GetApplicationID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApplicationID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetApplicationID indicates an expected call of GetApplicationID.
func (mr *MockDBOSContextMockRecorder) GetApplicationID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApplicationID", reflect.TypeOf((*MockDBOSContext)(nil).GetApplicationID))
}

// GetApplicationVersion mocks base method.
func (m *MockDBOSContext) GetApplicationVersion() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApplicationVersion")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetApplicationVersion indicates an expected call of GetApplicationVersion.
func (mr *MockDBOSContextMockRecorder) GetApplicationVersion() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApplicationVersion", reflect.TypeOf((*MockDBOSContext)(nil).GetApplicationVersion))
}

// GetEvent mocks base method.
func (m *MockDBOSContext) GetEvent(arg0 dbos.Client, targetWorkflowID, key string, timeout time.Duration) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEvent", arg0, targetWorkflowID, key, timeout)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEvent indicates an expected call of GetEvent.
func (mr *MockDBOSContextMockRecorder) GetEvent(arg0, targetWorkflowID, key, timeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEvent", reflect.TypeOf((*MockDBOSContext)(nil).GetEvent), arg0, targetWorkflowID, key, timeout)
}

// GetExecutorID mocks base method.
func (m *MockDBOSContext) GetExecutorID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExecutorID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetExecutorID indicates an expected call of GetExecutorID.
func (mr *MockDBOSContextMockRecorder) GetExecutorID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExecutorID", reflect.TypeOf((*MockDBOSContext)(nil).GetExecutorID))
}

// GetLatestApplicationVersion mocks base method.
func (m *MockDBOSContext) GetLatestApplicationVersion(arg0 dbos.Client) (dbos.VersionInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestApplicationVersion", arg0)
	ret0, _ := ret[0].(dbos.VersionInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestApplicationVersion indicates an expected call of GetLatestApplicationVersion.
func (mr *MockDBOSContextMockRecorder) GetLatestApplicationVersion(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestApplicationVersion", reflect.TypeOf((*MockDBOSContext)(nil).GetLatestApplicationVersion), arg0)
}

// GetSchedule mocks base method.
func (m *MockDBOSContext) GetSchedule(arg0 dbos.Client, scheduleName string) (dbos.WorkflowSchedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSchedule", arg0, scheduleName)
	ret0, _ := ret[0].(dbos.WorkflowSchedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSchedule indicates an expected call of GetSchedule.
func (mr *MockDBOSContextMockRecorder) GetSchedule(arg0, scheduleName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSchedule", reflect.TypeOf((*MockDBOSContext)(nil).GetSchedule), arg0, scheduleName)
}

// GetStepAggregates mocks base method.
func (m *MockDBOSContext) GetStepAggregates(arg0 dbos.Client, input dbos.GetStepAggregatesInput) ([]dbos.StepAggregateRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStepAggregates", arg0, input)
	ret0, _ := ret[0].([]dbos.StepAggregateRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStepAggregates indicates an expected call of GetStepAggregates.
func (mr *MockDBOSContextMockRecorder) GetStepAggregates(arg0, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStepAggregates", reflect.TypeOf((*MockDBOSContext)(nil).GetStepAggregates), arg0, input)
}

// GetStepID mocks base method.
func (m *MockDBOSContext) GetStepID() (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStepID")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStepID indicates an expected call of GetStepID.
func (mr *MockDBOSContextMockRecorder) GetStepID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStepID", reflect.TypeOf((*MockDBOSContext)(nil).GetStepID))
}

// GetWorkflowAggregates mocks base method.
func (m *MockDBOSContext) GetWorkflowAggregates(arg0 dbos.Client, input dbos.GetWorkflowAggregatesInput) ([]dbos.WorkflowAggregateRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkflowAggregates", arg0, input)
	ret0, _ := ret[0].([]dbos.WorkflowAggregateRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkflowAggregates indicates an expected call of GetWorkflowAggregates.
func (mr *MockDBOSContextMockRecorder) GetWorkflowAggregates(arg0, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkflowAggregates", reflect.TypeOf((*MockDBOSContext)(nil).GetWorkflowAggregates), arg0, input)
}

// GetWorkflowID mocks base method.
func (m *MockDBOSContext) GetWorkflowID() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkflowID")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkflowID indicates an expected call of GetWorkflowID.
func (mr *MockDBOSContextMockRecorder) GetWorkflowID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkflowID", reflect.TypeOf((*MockDBOSContext)(nil).GetWorkflowID))
}

// GetWorkflowSteps mocks base method.
func (m *MockDBOSContext) GetWorkflowSteps(arg0 dbos.Client, workflowID string, opts ...dbos.GetWorkflowStepsOption) ([]dbos.StepInfo, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, workflowID}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetWorkflowSteps", varargs...)
	ret0, _ := ret[0].([]dbos.StepInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkflowSteps indicates an expected call of GetWorkflowSteps.
func (mr *MockDBOSContextMockRecorder) GetWorkflowSteps(arg0, workflowID any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, workflowID}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkflowSteps", reflect.TypeOf((*MockDBOSContext)(nil).GetWorkflowSteps), varargs...)
}

// Go mocks base method.
func (m *MockDBOSContext) Go(arg0 dbos.Context, fn dbos.StepFunc, opts ...dbos.StepOption) (<-chan dbos.StepOutcome[any], error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, fn}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Go", varargs...)
	ret0, _ := ret[0].(<-chan dbos.StepOutcome[any])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Go indicates an expected call of Go.
func (mr *MockDBOSContextMockRecorder) Go(arg0, fn any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, fn}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Go", reflect.TypeOf((*MockDBOSContext)(nil).Go), varargs...)
}

// Launch mocks base method.
func (m *MockDBOSContext) Launch() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Launch")
	ret0, _ := ret[0].(error)
	return ret0
}

// Launch indicates an expected call of Launch.
func (mr *MockDBOSContextMockRecorder) Launch() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Launch", reflect.TypeOf((*MockDBOSContext)(nil).Launch))
}

// ListApplicationVersions mocks base method.
func (m *MockDBOSContext) ListApplicationVersions(arg0 dbos.Client) ([]dbos.VersionInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListApplicationVersions", arg0)
	ret0, _ := ret[0].([]dbos.VersionInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListApplicationVersions indicates an expected call of ListApplicationVersions.
func (mr *MockDBOSContextMockRecorder) ListApplicationVersions(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListApplicationVersions", reflect.TypeOf((*MockDBOSContext)(nil).ListApplicationVersions), arg0)
}

// ListQueues mocks base method.
func (m *MockDBOSContext) ListQueues(arg0 dbos.Client) ([]dbos.Queue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListQueues", arg0)
	ret0, _ := ret[0].([]dbos.Queue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListQueues indicates an expected call of ListQueues.
func (mr *MockDBOSContextMockRecorder) ListQueues(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListQueues", reflect.TypeOf((*MockDBOSContext)(nil).ListQueues), arg0)
}

// ListRegisteredWorkflows mocks base method.
func (m *MockDBOSContext) ListRegisteredWorkflows(arg0 dbos.Context) []dbos.WorkflowRegistryEntry {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRegisteredWorkflows", arg0)
	ret0, _ := ret[0].([]dbos.WorkflowRegistryEntry)
	return ret0
}

// ListRegisteredWorkflows indicates an expected call of ListRegisteredWorkflows.
func (mr *MockDBOSContextMockRecorder) ListRegisteredWorkflows(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRegisteredWorkflows", reflect.TypeOf((*MockDBOSContext)(nil).ListRegisteredWorkflows), arg0)
}

// ListSchedules mocks base method.
func (m *MockDBOSContext) ListSchedules(arg0 dbos.Client, opts ...dbos.ListSchedulesOption) ([]dbos.WorkflowSchedule, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListSchedules", varargs...)
	ret0, _ := ret[0].([]dbos.WorkflowSchedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSchedules indicates an expected call of ListSchedules.
func (mr *MockDBOSContextMockRecorder) ListSchedules(arg0 any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSchedules", reflect.TypeOf((*MockDBOSContext)(nil).ListSchedules), varargs...)
}

// ListWorkflows mocks base method.
func (m *MockDBOSContext) ListWorkflows(arg0 dbos.Client, opts ...dbos.ListWorkflowsOption) ([]dbos.WorkflowStatus, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListWorkflows", varargs...)
	ret0, _ := ret[0].([]dbos.WorkflowStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWorkflows indicates an expected call of ListWorkflows.
func (mr *MockDBOSContextMockRecorder) ListWorkflows(arg0 any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWorkflows", reflect.TypeOf((*MockDBOSContext)(nil).ListWorkflows), varargs...)
}

// ListenQueues mocks base method.
func (m *MockDBOSContext) ListenQueues(arg0 dbos.Context, names ...string) {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range names {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "ListenQueues", varargs...)
}

// ListenQueues indicates an expected call of ListenQueues.
func (mr *MockDBOSContextMockRecorder) ListenQueues(arg0 any, names ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, names...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListenQueues", reflect.TypeOf((*MockDBOSContext)(nil).ListenQueues), varargs...)
}

// ListenedQueues mocks base method.
func (m *MockDBOSContext) ListenedQueues(arg0 dbos.Context) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListenedQueues", arg0)
	ret0, _ := ret[0].([]string)
	return ret0
}

// ListenedQueues indicates an expected call of ListenedQueues.
func (mr *MockDBOSContextMockRecorder) ListenedQueues(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListenedQueues", reflect.TypeOf((*MockDBOSContext)(nil).ListenedQueues), arg0)
}

// Patch mocks base method.
func (m *MockDBOSContext) Patch(arg0 dbos.Context, patchName string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", arg0, patchName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Patch indicates an expected call of Patch.
func (mr *MockDBOSContextMockRecorder) Patch(arg0, patchName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockDBOSContext)(nil).Patch), arg0, patchName)
}

// PauseSchedule mocks base method.
func (m *MockDBOSContext) PauseSchedule(arg0 dbos.Client, scheduleName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PauseSchedule", arg0, scheduleName)
	ret0, _ := ret[0].(error)
	return ret0
}

// PauseSchedule indicates an expected call of PauseSchedule.
func (mr *MockDBOSContextMockRecorder) PauseSchedule(arg0, scheduleName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PauseSchedule", reflect.TypeOf((*MockDBOSContext)(nil).PauseSchedule), arg0, scheduleName)
}

// ReadStream mocks base method.
func (m *MockDBOSContext) ReadStream(arg0 dbos.Client, workflowID, key string, opts ...dbos.ReadStreamOption) ([]any, bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, workflowID, key}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ReadStream", varargs...)
	ret0, _ := ret[0].([]any)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ReadStream indicates an expected call of ReadStream.
func (mr *MockDBOSContextMockRecorder) ReadStream(arg0, workflowID, key any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, workflowID, key}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadStream", reflect.TypeOf((*MockDBOSContext)(nil).ReadStream), varargs...)
}

// ReadStreamAsync mocks base method.
func (m *MockDBOSContext) ReadStreamAsync(arg0 dbos.Client, workflowID, key string) (<-chan dbos.StreamValue[any], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadStreamAsync", arg0, workflowID, key)
	ret0, _ := ret[0].(<-chan dbos.StreamValue[any])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadStreamAsync indicates an expected call of ReadStreamAsync.
func (mr *MockDBOSContextMockRecorder) ReadStreamAsync(arg0, workflowID, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadStreamAsync", reflect.TypeOf((*MockDBOSContext)(nil).ReadStreamAsync), arg0, workflowID, key)
}

// Recv mocks base method.
func (m *MockDBOSContext) Recv(arg0 dbos.Context, topic string, timeout time.Duration) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv", arg0, topic, timeout)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockDBOSContextMockRecorder) Recv(arg0, topic, timeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockDBOSContext)(nil).Recv), arg0, topic, timeout)
}

// RegisterQueue mocks base method.
func (m *MockDBOSContext) RegisterQueue(arg0 dbos.Client, name string, options ...dbos.QueueOption) (dbos.Queue, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, name}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RegisterQueue", varargs...)
	ret0, _ := ret[0].(dbos.Queue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterQueue indicates an expected call of RegisterQueue.
func (mr *MockDBOSContextMockRecorder) RegisterQueue(arg0, name any, options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, name}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterQueue", reflect.TypeOf((*MockDBOSContext)(nil).RegisterQueue), varargs...)
}

// ResumeSchedule mocks base method.
func (m *MockDBOSContext) ResumeSchedule(arg0 dbos.Client, scheduleName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResumeSchedule", arg0, scheduleName)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResumeSchedule indicates an expected call of ResumeSchedule.
func (mr *MockDBOSContextMockRecorder) ResumeSchedule(arg0, scheduleName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResumeSchedule", reflect.TypeOf((*MockDBOSContext)(nil).ResumeSchedule), arg0, scheduleName)
}

// ResumeWorkflow mocks base method.
func (m *MockDBOSContext) ResumeWorkflow(arg0 dbos.Client, workflowID string, opts ...dbos.ResumeWorkflowOption) (dbos.WorkflowHandle[any], error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, workflowID}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ResumeWorkflow", varargs...)
	ret0, _ := ret[0].(dbos.WorkflowHandle[any])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResumeWorkflow indicates an expected call of ResumeWorkflow.
func (mr *MockDBOSContextMockRecorder) ResumeWorkflow(arg0, workflowID any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, workflowID}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResumeWorkflow", reflect.TypeOf((*MockDBOSContext)(nil).ResumeWorkflow), varargs...)
}

// ResumeWorkflows mocks base method.
func (m *MockDBOSContext) ResumeWorkflows(arg0 dbos.Client, workflowIDs []string, opts ...dbos.ResumeWorkflowOption) ([]dbos.WorkflowHandle[any], error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, workflowIDs}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ResumeWorkflows", varargs...)
	ret0, _ := ret[0].([]dbos.WorkflowHandle[any])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResumeWorkflows indicates an expected call of ResumeWorkflows.
func (mr *MockDBOSContextMockRecorder) ResumeWorkflows(arg0, workflowIDs any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, workflowIDs}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResumeWorkflows", reflect.TypeOf((*MockDBOSContext)(nil).ResumeWorkflows), varargs...)
}

// RetrieveQueue mocks base method.
func (m *MockDBOSContext) RetrieveQueue(arg0 dbos.Client, name string) (dbos.Queue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetrieveQueue", arg0, name)
	ret0, _ := ret[0].(dbos.Queue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RetrieveQueue indicates an expected call of RetrieveQueue.
func (mr *MockDBOSContextMockRecorder) RetrieveQueue(arg0, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetrieveQueue", reflect.TypeOf((*MockDBOSContext)(nil).RetrieveQueue), arg0, name)
}

// RetrieveWorkflow mocks base method.
func (m *MockDBOSContext) RetrieveWorkflow(arg0 dbos.Client, workflowID string) (dbos.WorkflowHandle[any], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetrieveWorkflow", arg0, workflowID)
	ret0, _ := ret[0].(dbos.WorkflowHandle[any])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RetrieveWorkflow indicates an expected call of RetrieveWorkflow.
func (mr *MockDBOSContextMockRecorder) RetrieveWorkflow(arg0, workflowID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetrieveWorkflow", reflect.TypeOf((*MockDBOSContext)(nil).RetrieveWorkflow), arg0, workflowID)
}

// RunAsStep mocks base method.
func (m *MockDBOSContext) RunAsStep(arg0 dbos.Context, fn dbos.StepFunc, opts ...dbos.StepOption) (any, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, fn}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunAsStep", varargs...)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunAsStep indicates an expected call of RunAsStep.
func (mr *MockDBOSContextMockRecorder) RunAsStep(arg0, fn any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, fn}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunAsStep", reflect.TypeOf((*MockDBOSContext)(nil).RunAsStep), varargs...)
}

// RunAsTransaction mocks base method.
func (m *MockDBOSContext) RunAsTransaction(arg0 dbos.Context, ds *dbos.DataSource, fn dbos.TxnFunc, opts ...dbos.StepOption) (any, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, ds, fn}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunAsTransaction", varargs...)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunAsTransaction indicates an expected call of RunAsTransaction.
func (mr *MockDBOSContextMockRecorder) RunAsTransaction(arg0, ds, fn any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, ds, fn}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunAsTransaction", reflect.TypeOf((*MockDBOSContext)(nil).RunAsTransaction), varargs...)
}

// RunWorkflow mocks base method.
func (m *MockDBOSContext) RunWorkflow(arg0 dbos.Context, fn dbos.WorkflowFunc, input any, opts ...dbos.WorkflowOption) (dbos.WorkflowHandle[any], error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, fn, input}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunWorkflow", varargs...)
	ret0, _ := ret[0].(dbos.WorkflowHandle[any])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunWorkflow indicates an expected call of RunWorkflow.
func (mr *MockDBOSContextMockRecorder) RunWorkflow(arg0, fn, input any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, fn, input}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunWorkflow", reflect.TypeOf((*MockDBOSContext)(nil).RunWorkflow), varargs...)
}

// Select mocks base method.
func (m *MockDBOSContext) Select(arg0 dbos.Context, channels []<-chan dbos.StepOutcome[any]) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Select", arg0, channels)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Select indicates an expected call of Select.
func (mr *MockDBOSContextMockRecorder) Select(arg0, channels any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*MockDBOSContext)(nil).Select), arg0, channels)
}

// Send mocks base method.
func (m *MockDBOSContext) Send(arg0 dbos.Client, destinationID string, message any, topic string, opts ...dbos.SendOption) error {
	m.ctrl.T.Helper()
	varargs := []any{arg0, destinationID, message, topic}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Send", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockDBOSContextMockRecorder) Send(arg0, destinationID, message, topic any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, destinationID, message, topic}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockDBOSContext)(nil).Send), varargs...)
}

// SetAlertHandler mocks base method.
func (m *MockDBOSContext) SetAlertHandler(handler dbos.AlertHandler) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetAlertHandler", handler)
}

// SetAlertHandler indicates an expected call of SetAlertHandler.
func (mr *MockDBOSContextMockRecorder) SetAlertHandler(handler any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAlertHandler", reflect.TypeOf((*MockDBOSContext)(nil).SetAlertHandler), handler)
}

// SetEvent mocks base method.
func (m *MockDBOSContext) SetEvent(arg0 dbos.Context, key string, message any, opts ...dbos.SetEventOption) error {
	m.ctrl.T.Helper()
	varargs := []any{arg0, key, message}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetEvent", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetEvent indicates an expected call of SetEvent.
func (mr *MockDBOSContextMockRecorder) SetEvent(arg0, key, message any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, key, message}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEvent", reflect.TypeOf((*MockDBOSContext)(nil).SetEvent), varargs...)
}

// SetLatestApplicationVersion mocks base method.
func (m *MockDBOSContext) SetLatestApplicationVersion(arg0 dbos.Client, versionName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLatestApplicationVersion", arg0, versionName)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLatestApplicationVersion indicates an expected call of SetLatestApplicationVersion.
func (mr *MockDBOSContextMockRecorder) SetLatestApplicationVersion(arg0, versionName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLatestApplicationVersion", reflect.TypeOf((*MockDBOSContext)(nil).SetLatestApplicationVersion), arg0, versionName)
}

// SetWorkflowAttributes mocks base method.
func (m *MockDBOSContext) SetWorkflowAttributes(arg0 dbos.Client, workflowID string, attributes map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetWorkflowAttributes", arg0, workflowID, attributes)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetWorkflowAttributes indicates an expected call of SetWorkflowAttributes.
func (mr *MockDBOSContextMockRecorder) SetWorkflowAttributes(arg0, workflowID, attributes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWorkflowAttributes", reflect.TypeOf((*MockDBOSContext)(nil).SetWorkflowAttributes), arg0, workflowID, attributes)
}

// SetWorkflowDelay mocks base method.
func (m *MockDBOSContext) SetWorkflowDelay(arg0 dbos.Client, workflowID string, opts ...dbos.SetWorkflowDelayOption) error {
	m.ctrl.T.Helper()
	varargs := []any{arg0, workflowID}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetWorkflowDelay", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetWorkflowDelay indicates an expected call of SetWorkflowDelay.
func (mr *MockDBOSContextMockRecorder) SetWorkflowDelay(arg0, workflowID any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, workflowID}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWorkflowDelay", reflect.TypeOf((*MockDBOSContext)(nil).SetWorkflowDelay), varargs...)
}

// Shutdown mocks base method.
func (m *MockDBOSContext) Shutdown(arg0 dbos.Client, timeout time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown", arg0, timeout)
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockDBOSContextMockRecorder) Shutdown(arg0, timeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockDBOSContext)(nil).Shutdown), arg0, timeout)
}

// Sleep mocks base method.
func (m *MockDBOSContext) Sleep(arg0 dbos.Context, duration time.Duration) (time.Duration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sleep", arg0, duration)
	ret0, _ := ret[0].(time.Duration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sleep indicates an expected call of Sleep.
func (mr *MockDBOSContextMockRecorder) Sleep(arg0, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sleep", reflect.TypeOf((*MockDBOSContext)(nil).Sleep), arg0, duration)
}

// TriggerSchedule mocks base method.
func (m *MockDBOSContext) TriggerSchedule(arg0 dbos.Client, scheduleName string) (dbos.WorkflowHandle[any], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TriggerSchedule", arg0, scheduleName)
	ret0, _ := ret[0].(dbos.WorkflowHandle[any])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TriggerSchedule indicates an expected call of TriggerSchedule.
func (mr *MockDBOSContextMockRecorder) TriggerSchedule(arg0, scheduleName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerSchedule", reflect.TypeOf((*MockDBOSContext)(nil).TriggerSchedule), arg0, scheduleName)
}

// Value mocks base method.
func (m *MockDBOSContext) Value(key any) any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Value", key)
	ret0, _ := ret[0].(any)
	return ret0
}

// Value indicates an expected call of Value.
func (mr *MockDBOSContextMockRecorder) Value(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Value", reflect.TypeOf((*MockDBOSContext)(nil).Value), key)
}

// WithCancel mocks base method.
func (m *MockDBOSContext) WithCancel() (dbos.Context, context.CancelFunc) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithCancel")
	ret0, _ := ret[0].(dbos.Context)
	ret1, _ := ret[1].(context.CancelFunc)
	return ret0, ret1
}

// WithCancel indicates an expected call of WithCancel.
func (mr *MockDBOSContextMockRecorder) WithCancel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithCancel", reflect.TypeOf((*MockDBOSContext)(nil).WithCancel))
}

// WithCancelCause mocks base method.
func (m *MockDBOSContext) WithCancelCause() (dbos.Context, context.CancelCauseFunc) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithCancelCause")
	ret0, _ := ret[0].(dbos.Context)
	ret1, _ := ret[1].(context.CancelCauseFunc)
	return ret0, ret1
}

// WithCancelCause indicates an expected call of WithCancelCause.
func (mr *MockDBOSContextMockRecorder) WithCancelCause() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithCancelCause", reflect.TypeOf((*MockDBOSContext)(nil).WithCancelCause))
}

// WithTimeout mocks base method.
func (m *MockDBOSContext) WithTimeout(arg0 dbos.Context, timeout time.Duration) (dbos.Context, context.CancelFunc) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTimeout", arg0, timeout)
	ret0, _ := ret[0].(dbos.Context)
	ret1, _ := ret[1].(context.CancelFunc)
	return ret0, ret1
}

// WithTimeout indicates an expected call of WithTimeout.
func (mr *MockDBOSContextMockRecorder) WithTimeout(arg0, timeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTimeout", reflect.TypeOf((*MockDBOSContext)(nil).WithTimeout), arg0, timeout)
}

// WithValue mocks base method.
func (m *MockDBOSContext) WithValue(key, val any) dbos.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithValue", key, val)
	ret0, _ := ret[0].(dbos.Context)
	return ret0
}

// WithValue indicates an expected call of WithValue.
func (mr *MockDBOSContextMockRecorder) WithValue(key, val any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithValue", reflect.TypeOf((*MockDBOSContext)(nil).WithValue), key, val)
}

// WithoutCancel mocks base method.
func (m *MockDBOSContext) WithoutCancel(arg0 dbos.Context) dbos.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithoutCancel", arg0)
	ret0, _ := ret[0].(dbos.Context)
	return ret0
}

// WithoutCancel indicates an expected call of WithoutCancel.
func (mr *MockDBOSContextMockRecorder) WithoutCancel(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithoutCancel", reflect.TypeOf((*MockDBOSContext)(nil).WithoutCancel), arg0)
}

// WriteStream mocks base method.
func (m *MockDBOSContext) WriteStream(arg0 dbos.Context, key string, value any, opts ...dbos.WriteStreamOption) error {
	m.ctrl.T.Helper()
	varargs := []any{arg0, key, value}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "WriteStream", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteStream indicates an expected call of WriteStream.
func (mr *MockDBOSContextMockRecorder) WriteStream(arg0, key, value any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, key, value}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteStream", reflect.TypeOf((*MockDBOSContext)(nil).WriteStream), varargs...)
}
