// Command sdlmerge concatenates the SDL documents under `schema/` into the one
// document gopgql reads.
//
// It exists because of a single gopgql limitation. `gopgql generate` takes
// `--sdl <file>`: one path, a plain string flag, not repeatable and not a
// directory ("read schema: read schema/: is a directory"). A property graph,
// though, can only span two PostgreSQL schemas if one document describes both
// — and SPEC.md §2.4 and §7.3 require exactly that, so that
// `Workflow ──HAS_SESSION──▶ Session` joins `dbos.workflow_status` to
// `agentiq.session` inside one `CREATE PROPERTY GRAPH`.
//
// Keeping SPEC.md §7.1 (the AgentIQ domain) and §7.3 (the read-only `dbos.*`
// projection) in one physical file would satisfy gopgql and lose the boundary
// that matters most in this repository: which tables AgentIQ owns and migrates,
// and which it only reads. So the two documents stay two documents and this
// program joins them for the generator.
//
// Delete it the day gopgql accepts more than one `--sdl`.
//
// The merge is textual and therefore hermetic: inputs are concatenated in the
// order given, separated by a banner naming the source, with no reordering and
// no reformatting. gopgql parses the result as one SDL document, which is
// legal because neither file redeclares a type, a scalar or a directive the
// other declares.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
)

func main() {
	out := flag.String("out", "", "path of the merged SDL document to write")
	flag.Parse()

	if err := run(*out, flag.Args()); err != nil {
		fmt.Fprintln(os.Stderr, "sdlmerge:", err)
		os.Exit(1)
	}
}

func run(out string, inputs []string) error {
	if out == "" {
		return fmt.Errorf("-out is required")
	}
	if len(inputs) == 0 {
		return fmt.Errorf("at least one input SDL document is required")
	}

	var buf bytes.Buffer
	buf.WriteString("# Code generated by tools/sdlmerge. DO NOT EDIT.\n")
	buf.WriteString("#\n")
	buf.WriteString("# The concatenation of the documents under schema/, which is what gopgql\n")
	buf.WriteString("# reads: `--sdl` takes one file, and a property graph spanning `dbos.*` and\n")
	buf.WriteString("# `agentiq.*` needs both described by one document. Edit the sources.\n")

	for _, in := range inputs {
		src, err := os.ReadFile(in)
		if err != nil {
			return err
		}
		// Report the source by its slash-separated path so the banner is the
		// same on every operating system, and the generated file does not
		// drift between a Linux CI run and a developer's machine.
		fmt.Fprintf(&buf, "\n# --- %s %s\n\n", filepath.ToSlash(in), banner)
		buf.Write(src)
		if len(src) > 0 && src[len(src)-1] != '\n' {
			buf.WriteByte('\n')
		}
	}

	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		return err
	}
	return os.WriteFile(out, buf.Bytes(), 0o644)
}

const banner = "------------------------------------------------------------"
